### PR TITLE
Initial apps

### PR DESCRIPTION
**Pull request by cassidyjames**
All of these are already in the repos and have good appdata

### CODE REVIEW

**Review by btkostner — CHANGES_REQUESTED** [review]
These are supposed to be appstream ids. They usually end with `.desktop`. Not sure if these are actually accurate. 

*EDIT*: they all just need `.desktop` at the end

**Review by btkostner — APPROVED** [review]
Never mind. I'm stupid. I forgot that we didn't do that with houston and AppCenter.

**Comment by cassidyjames** [comment]
:joy:

**Comment by btkostner** [comment]
`// TODO: change this`

**Pull request merged**
